services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443" # порты
    volumes: # кидаем ключи 
      - ./nginx/jenkins.local+1.pem:/etc/nginx/certs/jenkins.local+1.pem
      - ./nginx/jenkins.local+1-key.pem:/etc/nginx/certs/jenkins.local+1-key.pem
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: # не запустим без дженкинса
      - jenkins
  
  jenkins: # подключение дерриктории с докером для дженкинса
    build: ./jenkins
    container_name: jenkins
    ports: # прокид портов
      - "8080:8080"
      - "50000:50000"

    volumes: # сохраняем настройки дженкинса
      - ./jenkins/jenkins_home/jenkins_home:/var/jenkins_home # изменить если не монтируется добавить ./jenkins/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      JENKINS_OPTS: --httpPort=8080

volumes:
  jenkins_home:
    driver_opts:
      type: none
      device: ./jenkins/jenkins_home
      o: bind
